to-do
1. get information on number of queries (standardize this by candidate popularity??)
2. average num of gendered words
3. max num of gendered words
4. min number of gendered words
5. average length of query
6. num times query w most gendered language showed up? /popularity

In [17]:
import pandas as pd
import statistics

### Read in Candidate Info

In [18]:
cands = pd.read_csv('../candidates_info.csv')

In [19]:
cands

                      name           city gender race_detailed race_simplified
0              michelle wu         Boston      F         asian              nw
1          andrea campbell         Boston      F         black               w
2           dana depelteau         Boston      M         white               w
3   annissa essaibi george         Boston      F          arab              nw
4             jon santiago         Boston      M        latino              nw
5                kim janey         Boston      F         black              nw
6          michael bianchi         Boston      M         white               w
7              john barros         Boston      M         black              nw
8           scott stringer  New York City      M         white               w
9               eric adams  New York City      M         black              nw
10              maya wiley  New York City      F         black              nw
11           shaun donovan  New York City      M         white               w
12          kathryn garcia  New York City      F         white               w
13             ray mcguire  New York City      M         black              nw
14          dianne morales  New York City      F         black              nw
15             andrew yang  New York City      M         asian              nw
16         paperboy prince  New York City      N         black              nw
17            curtis sliwa  New York City      M         white               w
18          fernando mateo  New York City      M        latino              nw
19         isaac wright jr  New York City      M         black              nw
20               art chang  New York City      M         asian              nw
21        aaron foldenauer  New York City      M         white               w

### Add in query info

In [20]:
df = cands
#1. get information on number of queries (standardize this by candidate popularity??)
#2. average num of gendered words
#3. max num of gendered words
#4. min number of gendered words
#5. average length of query
#6. num times query w most gendered language showed up? /popularity
df['num_queries'] = ''
df['num_queries_unique'] = ''
df['num_gen'] = ''
df['avg_len'] = ''
df['avg_num_gen'] = ''
#df['min_num_gen'] = ''
#df['max_num_gen'] = ''

In [21]:
qs = pd.read_csv('all_queries_with_data.csv',index_col=False)
qs = qs.fillna("")
qs = qs.replace('annisa','annissa',regex=True)

In [36]:
qs[qs.city!='Boston']

,Query,Source,Date Added,city,seed_query,candidate,gender,gen_count
1,isaac wright jr daughter instagram,autocomplete,2021-04-27,NYC,isaac wright jr,isaac wright jr,M,1
3,scott stringer backgrounds,autocomplete,2021-04-27,NYC,scott stringer background,scott stringer,M,0
4,art chang mayor election results 2018,autocomplete,2021-04-27,NYC,art chang,art chang,M,0
5,mike bianchi omaha,autocomplete,2021-04-27,NYC,,,,0
7,andrew yang twitter chicken soup,autocomplete,2021-04-27,NYC,andrew yang,andrew yang,M,0
...,...,...,...,...,...,...,...,...
188767,nyc mayoral election 2021,related searches,2021-11-09,NYC,,,,0
188768,nyc mayoral race 2021 results,related searches,2021-11-09,NYC,,,,0
188769,nyc primary candidates 2021,related searches,2021-11-09,NYC,,,,0
188770,2013 nyc mayoral election,related searches,2021-11-09,NYC,,,,0
188771,nyc mayoral election 2017 results by neighborhood,related searches,2021-11-09,NYC,,,,0

Add count of gendered words to the query frame

In [23]:
#gendered lexicon
gen_set = ['wife','married','daughter','husband','partner','family','kids','love','son','father','mother','children',
          'boy','girl','marriage']

In [24]:
def add_gender_language(query):
    count = 0
    for word in gen_set:
        if word in query.lower(): 
            count = count+1
    return count

qs['gen_count'] = qs.Query.apply(add_gender_language)

In [25]:
def get_cand_queries(candidate):
    '''helper function that takes a candidate name and collects all queries searched about that candidate'''
    a = qs[qs.candidate==candidate]
    return a.Query.to_list()

In [26]:
def get_avg_gen_count(candidate):
    '''helper function that calculates the average number of gendered words in a query for a candidates'''
    a = qs[qs.candidate==candidate]
    return statistics.mean(a.gen_count.to_list())

In [27]:
def get_gen_count(candidate):
    '''helper function that calculates the percentage of candidate's queries that have at least one gendered word'''
    a = qs[(qs.candidate==candidate)&(qs.gen_count>0)]
    return len(a.gen_count.to_list())

In [28]:
df['num_queries'] = df['name'].apply(lambda x: len(get_cand_queries(x)))
df['num_queries_unique'] = df['name'].apply(lambda x: len(set(get_cand_queries(x))))
df['num_gen'] = df['name'].apply(lambda x: get_gen_count(x))
df['avg_len'] = df['name'].apply(lambda x: statistics.mean([len(query) for query in get_cand_queries(x)]))
df['avg_num_gen'] = df['name'].apply(lambda x: get_avg_gen_count(x))
#df['min_num_gen'] = ''
#df['max_num_gen'] = ''

In [29]:
#add in proportion of gendered language
df['percen_gen'] = df['num_gen'] / df['num_queries']

In [30]:
df

,name,city,gender,race_detailed,race_simplified,num_queries,num_queries_unique,num_gen,avg_len,avg_num_gen,percen_gen
0,michelle wu,Boston,F,asian,nw,21932,290,4362,21.444966,0.198887,0.198887
1,andrea campbell,Boston,F,black,w,21174,192,6707,25.391754,0.316756,0.316756
2,dana depelteau,Boston,M,white,w,8738,122,146,24.879950,0.016709,0.016709
3,annissa essaibi george,Boston,F,arab,nw,752,13,0,33.877660,0.000000,0.000000
4,jon santiago,Boston,M,latino,nw,15511,158,3469,22.632132,0.223648,0.223648
5,kim janey,Boston,F,black,nw,17226,199,5061,21.294729,0.293800,0.293800
6,michael bianchi,Boston,M,white,w,6793,90,28,24.988812,0.004122,0.004122
7,john barros,Boston,M,black,nw,18714,175,3528,21.138559,0.188522,0.188522
8,scott stringer,New York City,M,white,w,208,179,25,25.105769,0.120192,0.120192
9,eric adams,New York City,M,black,nw,15977,443,5589,19.005320,0.349815,0.349815
10,maya wiley,New York City,F,black,nw,277,196,34,23.083032,0.129964,0.122744
11,shaun donovan,New York City,M,white,w,143,143,8,25.853147,0.055944,0.055944
12,kathryn garcia,New York City,F,white,w,305,211,10,25.596721,0.032787,0.032787
13,ray mcguire,New York City,M,black,nw,156,156,19,24.833333,0.121795,0.121795
14,dianne morales,New York City,F,black,nw,148,147,6,26.222973,0.040541,0.040541
15,andrew yang,New York City,M,asian,nw,678,498,39,25.179941,0.057522,0.057522
16,paperboy prince,New York City,N,black,nw,62,62,62,25.822581,1.032258,1.000000
17,curtis sliwa,New York City,M,white,w,13408,248,669,22.615081,0.049896,0.049896
18,fernando mateo,New York City,M,latino,nw,125,106,4,24.664000,0.032000,0.032000
19,isaac wright jr,New York City,M,black,nw,228,227,62,29.609649,0.320175,0.271930
20,art chang,New York City,M,asian,nw,109,109,4,22.761468,0.036697,0.036697
21,aaron foldenauer,New York City,M,white,w,45,45,3,28.400000,0.066667,0.066667

In [31]:
df.to_csv('model_data.csv',index=False)

In [105]:
qs[qs.Query.str.contains('george')]

,Query,Source,Date Added,city,seed_query,candidate,gender,gen_count
30,annissa essaibi george bio,autocomplete,2021-04-27,NYC,,,,0
36,annissa essaibi george race 2020,autocomplete,2021-04-27,NYC,,,,0
90,annissa essaibi george lgbt,autocomplete,2021-04-27,NYC,,,,0
98,annissa essaibi george,autocomplete,2021-04-27,NYC,,,,0
107,annissa essaibi george mayoral election 2021,autocomplete,2021-04-27,NYC,,,,0
...,...,...,...,...,...,...,...,...
153708,annissa essaibi george siblings,related searches,2021-11-09,NYC,,,,0
153716,boston mayoral candidate george,related searches,2021-11-09,Boston,,,,0
153872,annissa essaibi george,related searches,2021-11-09,NYC,,,,0
153894,annissa essaibi george,related searches,2021-11-09,NYC,,,,0
154269,annissa essaibi george net worth,related searches,2021-11-09,NYC,,,,0